version: '3'
services:
  backend:
    build: .                  # Build the image from the current directory
    ports:
      - "5001:5000"           # Map port 5000 on your machine to port 5000 in the container
    volumes:
      - .:/app                # Mount the current directory to /app in the container
    command: python app.py    # Run the Flask application

