name: Forgot & Reset Password Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-forgot-reset:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask Flask-PyMongo Flask-JWT-Extended Flask-Bcrypt Flask-Cors pytest python-dotenv

      - name: Set environment variables from GitHub secrets
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> $GITHUB_ENV

      - name: Start Flask server
        env:
          FLASK_APP: app.py
          FLASK_RUN_HOST: 0.0.0.0
          FLASK_RUN_PORT: 5000
        run: |
          flask run &
          sleep 10  # Give it time to start

      # 1) Test Forgot Password with Existing User
      - name: Test forgot password (existing user)
        run: |
          curl --fail --show-error --verbose \
          -X POST http://127.0.0.1:5000/api/auth/forgot-password \
          -H "Content-Type: application/json" \
          -d '{"email":"testuser@example.com"}'
      
      # 2) Test Forgot Password with Non-Existing User
      - name: Test forgot password (non-existing user)
        run: |
          curl --fail --show-error --verbose \
          -X POST http://127.0.0.1:5000/api/auth/forgot-password \
          -H "Content-Type: application/json" \
          -d '{"email":"nonexistent@example.com"}' || echo "Expected 404 - user not found"
      
      # 3) Test Reset Password with an INVALID token to ensure we get 400
      - name: Test reset password (invalid token)
        run: |
          curl --fail --show-error --verbose \
          -X POST http://127.0.0.1:5000/api/auth/reset-password \
          -H "Content-Type: application/json" \
          -d '{"token":"fake_token","password":"NewPassword123"}' || echo "Expected 400 - invalid token"
